spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: insights.com
          jwk-set-uri: http://localhost:8080/jwks.json
  datasource:
    url: ${DATABASE_CONNECTION_STRING}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.SQLServerDialect
