spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: insights.com
          jwk-set-uri: http://localhost:8080/jwks.json
  datasource:
    url: jdbc:postgresql://vc-db.chulcebul0ir.eu-west-1.rds.amazonaws.com:5432/version_control_insights
    driver-class-name: org.postgresql.Driver
    username: vcadmin
    password: versioncontrol
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
