name: Build and Release JAR

on:
  workflow_dispatch:  
defaults:
  run:
    working-directory:
      client/source_control_insights_cli

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  
          java-version: '23'
          cache: 'maven'

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      - name: Get Latest Release Version
        id: get_version
        run: |
          echo "Latest version: $LATEST_VERSION"
          NEW_VERSION=$(echo $LATEST_VERSION | awk -F. '{print "v"$1"."$2"."$3+1}')
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: client/source_control_insights_cli/target/*.jar
          generateReleaseNotes: true
          name: "v1.0.0-SNAPSHOT"
          tag: "v1.0.0"
          draft: true
